version: "3.9"

services:
  velhia:
    container_name: velhia
    image: velhia
    environment:
      - "PORT=5000" 
    ports:
      - "5000:5000"
    volumes:
      - ./app:/VelhIA-API.API
    build:
      context: .
      dockerfile: Dockerfile